name: Auto-Merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    uses: ioBroker/testing-action-automerge/.github/workflows/automerge.yml@v1
